containers:
  bedrock:
    - name: minecraft_bedrock
      ssh: bedrock:2222
      passwordFile: /bedrock_sainus/.remote-console.yaml
      worlds:
        - /bedrock_sainus/worlds/sainus

schedule:
  startupDelay: 1m
  interval: 2h

  # Whenever a player logs in.
  onPlayerLogin: true
  # Whenever a player logs out.
  onPlayerLogout: true
  # Whenever the last player logs out
  onLastLogout: true
  # Limit backups to maximum once per 5 minutes
  minInterval: 5min

trim:
  trimDays: 2
  keepDays: 14
  minKeep: 2
